[package]
name = "abogen-mobile"
version.workspace = true
edition.workspace = true

[[bin]]
name = "abogen-mobile"
path = "src/main.rs"

[dependencies]
dioxus = { workspace = true, features = ["mobile"] }
abogen-ui = { path = "../../crates/ui" }

